[main]
font=JetBrainsMono NF:size=16
prompt=""
icons-enabled=true
lines=32
width=48
anchor=top

[colors]
background=252423ff
text=a89984ff
prompt=a89984ff
; placeholder=00ff00ff
input=d3869bff
match=7daea3ff
selection=3c3836ff
selection-text=a9b665ff
selection-match=d3869bff
; counter=0000ffff
border=504945ff

[border]
width=2
radius=0
